english_word_dictionary = [
    {"word": "Fixating",            "mean": "Sabitleme"},
    {"word": "Wedding Day",         "mean": "Düğün Günü"},
    {"word": "Whole",               "mean": "Tüm"},
    {"word": "Act",                 "mean": "Davranmak"},
    {"word": "Otherwise",           "mean": "Aksi Taktirde"},
    {"word": "Bring",               "mean": "Getirmek"},
    {"word": "Vulnerability",       "mean": "Güvenlik Açığı"},
    {"word": "Kook",                "mean": "Antika Tip"},
    {"word": "Cave",                "mean": "Mağara"},
    {"word": "Glacier",             "mean": "Buzul"},
    {"word": "Shoe",                "mean": "Ayakkabı"},
    {"word": "Instead of",          "mean": "Yerine"},
    {"word": "Issues",              "mean": "Sorunlar"},
    {"word": "Swallowing",          "mean": "Yutma"},
    {"word": "Ammunition",          "mean": "Mühimmat"},
    {"word": "Twirly",              "mean": "Moruk"},
    {"word": "As Far As",           "mean": "Kadarıyla"},
    {"word": "Engagement",          "mean": "Nişanlanmak"},
    {"word": "Fiance",              "mean": "Nişanlı"},
    {"word": "Stomped",             "mean": "Ezilmiş"},
    {"word": "Involved",            "mean": "Dahil Olmuş"},
    {"word": "Sonogram",            "mean": "Ultrason Cihazı"},
    {"word": "Deaf",                "mean": "Sağır"},
    {"word": "Gaging",              "mean": "Ölçme"},
    {"word": "Nodded",              "mean": "Başını salladı"},
    {"word": "Neither",             "mean": "Hiçbiri"},
    {"word": "Omnipotent",          "mean": "Her Şeye Gücü Yeten"},
    {"word": "Recently",            "mean": "Son Zamanlarda"},
    {"word": "Stand",               "mean": "Ayakta Durmak"},
    {"word": "A lot",               "mean": "Çok Fazla"},
    {"word": "Relieved",            "mean": "Rahatlamak"},
    {"word": "Nervous",             "mean": "Gergin"},
    {"word": "Decided",             "mean": "Kararlı"},
    {"word": "Preferred",           "mean": "Tercihli"},
    {"word": "If Only",             "mean": "Keşke"},
    {"word": "Waitress",            "mean": "Bayan Garson"},
    {"word": "Snort",               "mean": "Burundan"},
    {"word": "Eager",               "mean": "İstekli"},
    {"word": "Flaw",                "mean": "Kusur"},
    {"word": "Even",                "mean": "Eşit"},
    {"word": "Pee",                 "mean": "İşemek"},
    {"word": "Raise",               "mean": "Artırmak"},
    {"word": "Adore",               "mean": "Hayranlık Duymak"},
    {"word": "Expression",          "mean": "İfade"},
    {"word": "Innate",              "mean": "Doğuştan"},
    {"word": "Selfish",             "mean": "Bencil"},
    {"word": "Measured",            "mean": "Ölçülen"},
    {"word": "Manner",              "mean": "Biçim"},
    {"word": "Yardstick",           "mean": "Kıstas"},
    {"word": "Clattering",          "mean": "Takırtı"},
    {"word": "Decisions",           "mean": "Kararlar"},
    {"word": "Instance",            "mean": "Misal"},
    {"word": "Cheap",               "mean": "Ucuz"},
    {"word": "Went",                "mean": "Gitmiş"},
    {"word": "Plugs",               "mean": "Fişler"},
    {"word": "Particular",          "mean": "Özel"},
    {"word": "Enterprise",          "mean": "Girişim"},
    {"word": "Welling",             "mean": "İyileşme"},
    {"word": "Can",                 "mean": "Kutu"},
    {"word": "I already am",        "mean": "Zaten öyleyim"},
    {"word": "Cushions",            "mean": "Kırlent Yastık"},
    {"word": "Prep",                "mean": "Hazırlık"},
    {"word": "Wrist",               "mean": "Bilek"},
    {"word": "Distance",            "mean": "Mesafe"},
    {"word": "Ridiculous",          "mean": "Saçma"},
    {"word": "Thumb",               "mean": "Baş Parmak"},
    {"word": "Spent",               "mean": "Harcamak"},
    {"word": "Pair",                "mean": "Çift"},
    {"word": "Puke",                "mean": "Kusmak"},
    {"word": "Inconvenience",       "mean": "Rahatsızlık"},
    {"word": "Crook",               "mean": "Dolandırıcı"},
    {"word": "Peek",                "mean": "Dikizlemek"},
    {"word": "Blobies",             "mean": "Lekeler"},
    {"word": "Bean",                "mean": "Fasulye"},
    {"word": "Beep",                "mean": "Biplemek"},
    {"word": "Satisfied",           "mean": "Memnun"},
    {"word": "Reach",               "mean": "Ulaşmak"},
    {"word": "Breasts",             "mean": "Göğüsler"},
    {"word": "Scrunchy",            "mean": "Toka"},
    {"word": "Downstairs",          "mean": "Alt Kat"},
    {"word": "Choruses",            "mean": "Korolar"},
    {"word": "Dumped",              "mean": "Terk Etmek"},
    {"word": "Beanstalk",           "mean": "Fasulye Sırığı"},
    {"word": "Floppy",              "mean": "Sarkık"},
    {"word": "Predicament",         "mean": "Çıkmaz Durum"},
    {"word": "Dented",              "mean": "Ezik"},
    {"word": "Towel",               "mean": "Havlu"},
    {"word": "Preppy",              "mean": "Tiki"},
    {"word": "Attractive",          "mean": "Çekici"},
    {"word": "Seems",               "mean": "Öyle Gibi"},
    {"word": "Glamour",             "mean": "Cazibe"},
    {"word": "Freakish",            "mean": "Garip"},
    {"word": "Coincidence",         "mean": "Tesadüf"},
    {"word": "Laundry",             "mean": "Çamaşır"},
    {"word": "Laying",              "mean": "Döşeme"},
    {"word": "Tile",                "mean": "Fayans"},
    {"word": "Shave",               "mean": "Traş olmak"},
    {"word": "Snuggles",            "mean": "Sarılmak"},
    {"word": "Suds",                "mean": "Köpük"},
    {"word": "Separate",            "mean": "Ayırmak"},
    {"word": "Delicate",            "mean": "Narin"},
    {"word": "Noise",               "mean": "Gürültü"},
    {"word": "Squirrel",            "mean": "Sincap"},
    {"word": "Weasel",              "mean": "Gelincik"},
    {"word": "Terrific",            "mean": "Müthiş"},
    {"word": "Sock",                "mean": "Çorap"},
    {"word": "Inappropriate",       "mean": "Uygunsuz"},
    {"word": "Ought",               "mean": "Gerekli"},
    {"word": "Divorced",            "mean": "Boşanmış"},
    {"word": "Borrow",              "mean": "Borç Almak"},
    {"word": "Moisturizer",         "mean": "Nemlendirici"},
    {"word": "Scurb",               "mean": "Kaldırım Taşı"},
    {"word": "Pan",                 "mean": "Tava"},
    {"word": "Strewn",              "mean": "Saçılmış"},
    {"word": "Reckless",            "mean": "Pervasız"},
    {"word": "Haphazard",           "mean": "Gelişigüzel"},

    # {"word": "",             "mean": ""},
]
