english_word_dictionary = [
    {"word": "Stork",               "mean": "Leylek"},
    {"word": "Squirrel",            "mean": "Sincap"},
    {"word": "Herd",                "mean": "Sürü"},
    {"word": "Cottage",             "mean": "Köy Evi"},
    {"word": "Farm",                "mean": "Çiftlik"},
    {"word": "Landscape",           "mean": "Manzara"},
    {"word": "Detached",            "mean": "Müstakil"},
    {"word": "Forget",              "mean": "Unutmak"},
    {"word": "Kook",                "mean": "Antika Tip"},
    {"word": "Whole",               "mean": "Tüm"},
    {"word": "Cave",                "mean": "Mağara"},
    {"word": "Glacier",             "mean": "Buzul"},
    {"word": "Shoe",                "mean": "Ayakkabı"},
    {"word": "Barrage",             "mean": "Baraj"},
    {"word": "Issue",               "mean": "Sorun"},
    {"word": "Wedding",             "mean": "Düğün"},
    {"word": "Haphazard",           "mean": "Gelişigüzel"},
    {"word": "Act",                 "mean": "Davranmak"},
    {"word": "Vulnerability",       "mean": "Güvenlik Açığı"},
    {"word": "Otherwise",           "mean": "Aksi Takdirde"},
    {"word": "Bring",               "mean": "Getirmek"},
    {"word": "Stand",               "mean": "Durmak"},
    {"word": "Fixate",              "mean": "Sabitlemek"},
    {"word": "Cheap",               "mean": "Ucuz"},
    {"word": "Plug",                "mean": "Tıpa"},
    {"word": "Crook",               "mean": "Dolandırıcı"},
    {"word": "Waitress",            "mean": "Kadın Garson"},
    {"word": "Enterprise",          "mean": "Girişim"},
    {"word": "Sort",                "mean": "Çeşit"},
    {"word": "Waiter",              "mean": "Garson"},
    {"word": "Reckless",            "mean": "Pervasız"},
    {"word": "Sonogram",            "mean": "Ultrason Cihazı"},
    {"word": "Downstairs",          "mean": "Alt Kat"},
    {"word": "Even",                "mean": "Eşit"},
    {"word": "Engagement",          "mean": "Nişan"},
    {"word": "Engage",              "mean": "Bağlanmak"},
    {"word": "Omnipotent",          "mean": "Her Şeye Gücü Yeten"},
    {"word": "Can",                 "mean": "Kutu"},
    {"word": "Prep",                "mean": "Hazırlık"},
    {"word": "Pan",                 "mean": "Tava"},
    {"word": "Pee",                 "mean": "İşemek"},
    {"word": "Bean",                "mean": "Fasulye"},
    {"word": "Beanstalk",           "mean": "Fasulye Sırığı"},
    {"word": "Cushion",             "mean": "Minder"},
    {"word": "Deaf",                "mean": "Sağır"},
    {"word": "Pair",                "mean": "Çift"},
    {"word": "Puke",                "mean": "Kusmak"},
    {"word": "Peek",                "mean": "Dikizlemek"},
    {"word": "Distance",            "mean": "Mesafe"},
    {"word": "Smell",               "mean": "Koku"},
    {"word": "Spell",               "mean": "Hecelemek"},
    {"word": "Rare",                "mean": "Nadir"},
    {"word": "Common",              "mean": "Yaygın"},
    {"word": "Mark",                "mean": "İşaret"},
    {"word": "Produce",             "mean": "Üretmek"},
    {"word": "Strive",              "mean": "Çabalamak"},
    {"word": "Improve",             "mean": "Geliştirmek"},
    {"word": "Earn",                "mean": "Para Kazanmak"},
    {"word": "Wrist",               "mean": "Bilek"},
    {"word": "Bowl",                "mean": "Tas"},
    {"word": "Opposite",            "mean": "Zıt"},
    {"word": "Sailor",              "mean": "Denizci"},
    {"word": "Sailed",              "mean": "Yelken Açmak"},
    {"word": "Umbrella",            "mean": "Şemsiye"},
    {"word": "Introduce",           "mean": "Tanıtmak"},
    {"word": "Invention",           "mean": "Buluş"},
    {"word": "Debt",                "mean": "Borç"},
    {"word": "Admire",              "mean": "Hayran Olmak"},
    {"word": "Journey",             "mean": "Seyahat"},
    {"word": "Glad",                "mean": "Memnun"},
    {"word": "Chair",               "mean": "Sandalye"},
    {"word": "Stair",               "mean": "Merdiven"},
    {"word": "Separate",            "mean": "Ayırmak"},
    {"word": "Weather",             "mean": "Hava Durumu"},
    {"word": "Shine",               "mean": "Parlamak"},
    {"word": "Sock",                "mean": "Çorap"},
    {"word": "Routine",             "mean": "Rutin"},
    {"word": "Stable",              "mean": "Stabil"},
    {"word": "Dubbing",             "mean": "Dublaj"},
    {"word": "Subtitle",            "mean": "Altyazı"},
    {"word": "Possible",            "mean": "Mümkün"},
    {"word": "Nest",                "mean": "Yuva"},
    {"word": "Different",           "mean": "Farklı"},
    {"word": "Pillow",              "mean": "Yastık"},
    {"word": "Relieve",             "mean": "Rahatlamak"},
    {"word": "Yardstick",           "mean": "Kıstas"},
    {"word": "Inconvenience",       "mean": "Rahatsızlık"},
    {"word": "Measure",             "mean": "Ölçüm"},
    {"word": "Spend",               "mean": "Harcamak"},
    {"word": "Particular",          "mean": "Özel"},
    {"word": "Strewn",              "mean": "Dağılmış"},
    {"word": "Borrow",              "mean": "Ödünç Almak"},
    {"word": "Decide",              "mean": "Karar Vermek"},
    {"word": "Instance",            "mean": "Örnek"},
    {"word": "Decision",            "mean": "Karar"},
    {"word": "Dumped",              "mean": "Terk Etmek"},
    {"word": "Snort",               "mean": "Burnundan Solumak"},
    {"word": "Innate",              "mean": "Doğuştan"},
    {"word": "Flaw",                "mean": "Kusur"},
    {"word": "Thumb",               "mean": "Baş Parmak"},
    {"word": "Ridiculous",          "mean": "Gülünç"},
    {"word": "Adore",               "mean": "Tapmak"},
    {"word": "Eager",               "mean": "İstekli"},
    {"word": "Satisfied",           "mean": "Memnun"},
    {"word": "Reach",               "mean": "Ulaşmak"},
    {"word": "Breast",              "mean": "Göğüs"},
    {"word": "Scrunchy",            "mean": "Toka"},
    {"word": "Chorus",              "mean": "Koro"},
    {"word": "Twirly",              "mean": "Moruk"},
    {"word": "Ammunition",          "mean": "Mühimmat"},
    {"word": "Swallow",             "mean": "Yutmak"},
    {"word": "Weasel",              "mean": "Gelincik"},
    {"word": "Consist",             "mean": "Oluşmak"},

    # {"word": "",             "mean": ""},
]